### PR TITLE
Preserve first dot of relateve dir name. (Fix #5)

### LINKED ISSUE #5: Should not change relative dir name.
# Expect behavior

```ts
const replaceExt = require('replace-ext');

console.log(replaceExt('a/b/c.js', '.ts'));
console.log(replaceExt('./a/b/c.js', '.ts'));
console.log(replaceExt('../a/b/c.js', '.ts'));
```

Should log

 ```
a/b/c.ts
./a/b/c.ts
../a/b/c.ts
```

# Current behavior

Log 

 ```
a/b/c.ts
a/b/c.ts // this line changed
../a/b/c.ts
```

# What went wrong

`replace-ext` should only replace extension name without change other parts of path.

For example if I use `replace-ext` in Babel to transform all `import` statement in ES Module.

`import 'lodash/add.js'` => `import 'lodash/add.ts'`

doesn't equal to 

`import './lodash/add.js'` => `import 'lodash/add.ts'`

because `lodash/add.ts` is a package in node_modules but `./lodash/add.ts` is in sub dir.

# Reference

See how `path.parse` and `path.format` works:

```ts
const path = require('path');
const pathObj = path.parse('./a/b/c.js');
pathObj.ext = '.ts';
console.log(path.format(pathObj)); // output `./a/b/c.js`
```

### PR DESCRIPTION
**Pull request by sttk**
This pr is to fix the issue #5, and base on the pr #6.

### CODE REVIEW

**Comment by malash** [comment]
LGTM

Any one can help stamp this PR ? @phated @erikkemperman @contra

**Comment by erikkemperman** [comment]
I haven’t looked at the scaffolding part carefully (don’t know anything about azure pipelines) but the core part about period prefix looks good to me!

**Comment by phated** [comment]
Sorry for the delay here. Getting this merged now.

**Comment by sttk** [comment]
@phated Thanks for merging!

**Pull request merged**
